name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Set image name
      - name: Set image name
        run: echo "IMAGE_NAME=kgpmask/mask" >> $GITHUB_ENV

      # 4. Build Docker image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.ref_name }} .

      # 5. Push images
      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ github.ref_name }}
